server:
  port: 7000

spring:
  #데이터베이스 설정
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@${db.host}:${db.port}:XE
    username: ${db.username}
    password: ${db.password}

  #JPA 설정
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddlAuto: create

  devtools:


# 로거 설정
logging:
  level:
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace



# 액추에이터 설정
management:
  endpoint:
    health:
      showDetails: always
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, refresh


# JWT 설정
jwt:
  secret: ${jwtSecret}
  validSeconds: ${jwtValidSeconds}

cors:
  allow:
    origins:
      - http://localhost:7000
      - http://localhost:7001

springdoc:
  version: '1.0.0'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /apidocs.html
    disable-swagger-default-url: true
  paths-to-match:
    - /**